// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	InsertFile(ctx context.Context, arg InsertFileParams) (File, error)
}

var _ Querier = (*Queries)(nil)
