// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, arg DeleteUserParams) (User, error)
	GetFile(ctx context.Context, arg GetFileParams) ([]string, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	GetUsersAsc(ctx context.Context, arg GetUsersAscParams) ([]User, error)
	GetUsersDesc(ctx context.Context, arg GetUsersDescParams) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
