FROM golang:latest

# Set destination for COPY
WORKDIR /file-search

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/reference/dockerfile/#copy
COPY . .

# Build
RUN go build -o /main.exe ./file-search/main.go

EXPOSE 8082

# Run
CMD ["/main.exe"]