services:
  server:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile.grpc.server
    command: [ "/grpc-server.exe", "-port", "8080" ]
    ports:
      - "8080:8080"
    volumes:
      - ./file-index:/grpc-server/C/

  # client:
  #   build:
  #     context: .
  #     dockerfile: ./deployment/Dockerfile.grpc.client
  #   command: [ "/grpc-client.exe", "-address", "172.20.176.1:8080" ]
  #   volumes:
  #     - ./cert:/grpc-client/cert
  #   depends_on:
  #     - server

  api:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile.api
    ports:
      - "8082:8082"
    depends_on:
      - server
    volumes:
      - ./app.env:/file-search/app.env
  # postgres:
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=root
  #     - POSTGRES_PASSWORD=secret
  #     - POSTGRES_DB=everything_pg
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - data-volume:/var/lib/postgresql/data
