// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, arg DeleteUserParams) (User, error)
	// If limit is not provided, return all results
	GetFiles(ctx context.Context, arg GetFilesParams) ([]string, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsersAsc(ctx context.Context, arg GetUsersAscParams) ([]User, error)
	GetUsersDesc(ctx context.Context, arg GetUsersDescParams) ([]User, error)
	InsertFile(ctx context.Context, arg InsertFileParams) (File, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
