FROM golang:latest

# Set destination for COPY
WORKDIR /grpc-client

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/reference/dockerfile/#copy
COPY . .

# Build
RUN CGO_ENABLED=0 GOOS=windows go build -o /grpc-client.exe ./file-index/cmd/client/main.go

EXPOSE 8080

# Run
CMD ["/grpc-client.exe"]