// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: service_download.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DownloadFile_CreateDownload_FullMethodName = "/download_filesystem.DownloadFile/CreateDownload"
)

// DownloadFileClient is the client API for DownloadFile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DownloadFileClient interface {
	CreateDownload(ctx context.Context, in *CreateDownloadRequest, opts ...grpc.CallOption) (*CreateDownloadResponse, error)
}

type downloadFileClient struct {
	cc grpc.ClientConnInterface
}

func NewDownloadFileClient(cc grpc.ClientConnInterface) DownloadFileClient {
	return &downloadFileClient{cc}
}

func (c *downloadFileClient) CreateDownload(ctx context.Context, in *CreateDownloadRequest, opts ...grpc.CallOption) (*CreateDownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDownloadResponse)
	err := c.cc.Invoke(ctx, DownloadFile_CreateDownload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DownloadFileServer is the server API for DownloadFile service.
// All implementations must embed UnimplementedDownloadFileServer
// for forward compatibility.
type DownloadFileServer interface {
	CreateDownload(context.Context, *CreateDownloadRequest) (*CreateDownloadResponse, error)
	mustEmbedUnimplementedDownloadFileServer()
}

// UnimplementedDownloadFileServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDownloadFileServer struct{}

func (UnimplementedDownloadFileServer) CreateDownload(context.Context, *CreateDownloadRequest) (*CreateDownloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDownload not implemented")
}
func (UnimplementedDownloadFileServer) mustEmbedUnimplementedDownloadFileServer() {}
func (UnimplementedDownloadFileServer) testEmbeddedByValue()                      {}

// UnsafeDownloadFileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DownloadFileServer will
// result in compilation errors.
type UnsafeDownloadFileServer interface {
	mustEmbedUnimplementedDownloadFileServer()
}

func RegisterDownloadFileServer(s grpc.ServiceRegistrar, srv DownloadFileServer) {
	// If the following call pancis, it indicates UnimplementedDownloadFileServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DownloadFile_ServiceDesc, srv)
}

func _DownloadFile_CreateDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadFileServer).CreateDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DownloadFile_CreateDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadFileServer).CreateDownload(ctx, req.(*CreateDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DownloadFile_ServiceDesc is the grpc.ServiceDesc for DownloadFile service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DownloadFile_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "download_filesystem.DownloadFile",
	HandlerType: (*DownloadFileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDownload",
			Handler:    _DownloadFile_CreateDownload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_download.proto",
}
